const alienAnswer = {

	en: [
	    "Attention! 51 percent that the object is an alien!",
	    "DNA structure shows that the ancestors of the object are of extraterrestrial origin",
	    "An unknown substance was detected in the blood set, probably this object has a UFO concern",
	    "radioactive background says that among the friends of the object is alien",
	    "high level of unknown radiation, someone is trying to fool you, try again",
	    "Either the object has recently dealt with an alien or he is an alien himself",
	    "Scanning the object's eyes detected that he had recently seen an alien in Human Form",
	    "The object does not suspect this, but he has an alien in his family",
	    "gamma radiation exceeds the norm, very likely, we are dealing with an object of unearthly origin",
	   	"There are suspicions that the object's memory was rewritten, and in his past he knew someone's secret",
	   	
	   	"The energetic field of the object contains unknown radiation, possibly from his friends",
		"Scanning detected that the object's clothing was touching the alien",
		"Unknown radiation detected, repeat scanning",
		"According to scan data, the object is dealing with the phenomenon of extraterrestrial existence",
		"The subconscious of the object hides a very important secret",
		"The object's subconscious is based, let's repeat the scan",
		"Let the object show the number three with your fingers, and repeat the scan",
		"Switch to truth detector mode, and let the object answer the question if he likes green",
		"One hundred percent that the object comes from our solar system, but it is not sure from which planet",
		"Scanning shows that the object has telepathic abilities, it just doesn't know it or doesn't admit it",
		"Memory research shows that there is at least one extraterrestrial person in the everyday environment of the object",
		"Scanning the energy field of an object is very similar to the energy field in zone 51"
	],

	pl:[
		"Uwaga! 51 procent, że obiekt jest kosmitą!",
		"Struktura DNA pokazuje, że przodkowie obiektu są pochodzenia pozaziemskiego",
		"W zestawie krwi wykryto nieznaną substancję, prawdopodobnie ten objekt ma doczynienie do ufo",
		"radioaktywne tło mówi, że spośród przyjacieli objekta jest obcy",
		"wysoki poziom nieznanego promieniowania, ktoś Ciebie próbuje zmyliić, spróbuj jeszcze raz",
		"Albo obiekt miał niedawno doczynienia z obcym, albo on sam jest kosmitą",
		"Skanowanie oczu obiektu wykryło, że on niedawno widział kosmitę w Postaci człowieka",
		"Obiekt tego nie podejrzewa, ale on ma w rodzinie kosmitę",
		"promieniowanie gamma przekracza normę, duże prawdzopodobieństwo, że mamy doczynienie z obiektem nieziemskiego pochodzenia",
		"Są podejrzenia, że pamięć obiekta była przepisana, i w swojej przeszłości on wiedział czyjąś tajemnicę",

		"Energietyczne pole obiektu zawiera nieznane promieniowanie, możliwie ono pochodzi od jego znajomych",
		"Skanowanie wykryło, że odzież obiekta dotykał kosmita",
		"Wykryto nieznane promieniowanie, powtóż skanowanie",
		"Według danych skanowania obiekt ma doczynienia z fomą pozaziemskiego istnienia",
		"Podświadomość obiektu ukrywa bardzo ważną tajemnicę",
		"Podświadomość obiektu opiera się, powtóżmy skanowanie",
		"Niech obiekt pokaże palcami cyfrę trzy, i powtóż skanowanie",
		"Przełącz na tryb detektor prawdy, i niech obiekt odpowie na pytanie, czy on lubi zielony kolor",
		"Sto procent, że obiekt pochodzi z naszego Układu Słonecznego, ale nie ma pewności z jakiej planety",
		"Skanowanie pokazuje, że obiekt ma zdolności telepatyczne, tylko nie wie o tym, albo nie przyznaje się do tego",
		"Badanie pamięci pokazuje, że w codziennym otoczeniu obiekta istnieje minimum jedna osoba pozaziemska",
		"Skanowanie pola energetycznego obiektu jest bardzo podobne do pola energetycznego w strefie 51"
	],

	ru: [
		"Внимание! 51 процент что объект инопланетянин!",
		"Структура ДНК показывает, что предки объекта имеют внеземное происхождение",
		"В составе крови было обнаружено неизвестное вещество, вероятно, этот объект имеет отношение к НЛО",
		"Радиоактивный фон говорит о том, что среди друзей объекта находится инопланетянин",
		"высокий уровень неизвестного излучения, кто-то пытается обмануть вас, попробуйте еще раз",
		"Либо объект недавно имел дело с инопланетянином, либо он сам является инопланетянином",
		"Сканирование глаз показывает, что объект недавно видел инопланетянина в облике человека",
		"Обьект не подозревает об этом, но в его семье есть инопланетянин",
		"гамма-излучение превышает норму, очень вероятно, что нам приходится иметь дело с объектом неземного происхождения",
		"Есть подозрения, что память объекта была переписана, и в прошлом он знал чей-то секрет",

		"Энергетическое поле объекта содержит неизвестное излучение, возможно, от его друзей",
		"Сканирование обнаружило, что одежда объекта касалась пришельца",
		"Обнаружено неизвестное излучение, повторите сканирование",
		"Согласно данным сканирования, объект имеет дело с явлением внеземного существования",
		"Подсознание объекта скрывает очень важный секрет",
		"Подсознание объекта основано, давайте повторим сканирование",
		"Пусть объект покажет пальцем номер три и повторите сканирование",
		"Переключитесь в режим детектора правды, и пусть объект ответит на вопрос, нравится ли ему зеленый",
		"На сто процентов этот объект происходит из нашей солнечной системы, но неясно, с какой это планеты",
		"Сканирование показывает, что объект обладает телепатическими способностями, он просто не знает об этом или не признает это",
		"Исследования памяти показывают, что в повседневной среде объекта есть как минимум один инопланетянин",
		"Сканирование энергетического поля объекта очень похоже на энергетическое поле в зоне 51"
	],

	ja: [
		"注意！ オブジェクトがエイリアンであると51％！",
		"DNA構造は、オブジェクトの祖先が地球外起源であることを示しています",
		"血液セットに未知の物質が検出されました。おそらくこのオブジェクトにはUFOの懸念があります",
		"放射能の背景は、オブジェクトの友人の間で外国人であると言います",
		"高レベルの未知の放射線、誰かがあなたをだまそうとしている、もう一度試してください",
		"オブジェクトが最近エイリアンに対処したか、彼自身がエイリアンです",
		"アイスキャンは、オブジェクトが最近、人を装ってエイリアンを見たことを示しています。",
		"オブジェクトはこれを疑っていませんが、彼は彼の家族に外国人を持っています",
		"ガンマ線が標準を超えている可能性が非常に高い。",
		"オブジェクトの記憶が書き換えられた疑いがあり、彼の過去には誰かの秘密を知っていた",
		
		"物体のエネルギー場には、おそらく彼の友人からの未知の放射線が含まれています",
		"オブジェクトの服がエイリアンに触れていることをスキャンで検出しました",
		"未知の放射線が検出されました。スキャンを繰り返してください",
		"スキャンデータによると、オブジェクトは地球外の存在の現象を扱っています",
		"オブジェクトの潜在意識は非常に重要な秘密を隠します",
		"オブジェクトの潜在意識は基づいています。スキャンを繰り返しましょう",
		"オブジェクトに指で3番を表示させ、スキャンを繰り返します",
		"真理値検出モードに切り替えて、オブジェクトが緑が好きなら質問に答えさせてください",
		"オブジェクトが私たちの太陽系から来ていることは100％ですが、どの惑星からのものかはわかりません",
		"スキャンは、オブジェクトがテレパシー能力を持っていることを示します。それは単にそれを知らないか、認めないだけです",
		"記憶の研究は、対象の日常環境に少なくとも1人の地球外の人がいることを示しています",
		"物体のエネルギー場のスキャンは、ゾーン51のエネルギー場に非常に似ています"
	],

	zh: [
		"注意！ 51％的对象是外星人！",
		"DNA结构表明该对象的祖先是外星起源的",
		"在血液中检测到未知物质，可能是不明飞行物",
		"放射性背景说，物体的朋友之中是外星人",
		"高水平的未知辐射，有人试图欺骗您，然后重试",
		"该物体最近已与一个外星人打交道，或者他本人是外星人",
		"扫描物体的眼睛发现他最近看见了一个人类形态的外星人",
		"该物体不怀疑这一点，但是他的家人中有一个外星人",
		"伽玛射线超出正常范围，很可能是我们正在处理一个超自然起源的物体",
		"有人怀疑物体的记忆被重写了，在他过去，他知道某人的秘密",
		"物体的高能场包含未知的辐射，可能来自他的朋友",
		"扫描发现物体的衣服正在碰到外星人",
		"检测到未知辐射，重复扫描",
		"根据扫描数据，该物体正在处理外星人存在的现象",
		"物体的潜意识隐藏了一个非常重要的秘密",
		"对象的潜意识是基于的，让我们重复扫描",
		"让对象用手指显示数字三，然后重复扫描",
		"切换到真相检测器模式，让对象回答他是否喜欢绿色的问题",
		"百分之一百的物体来自我们的太阳系，但不确定来自哪个行星",
		"扫描显示该物体具有心灵感应能力，它只是不知道或不承认它。",
		"记忆研究表明，在物体的日常环境中至少有一个外星人",
		"扫描物体的能量场与区域51中的能量场非常相似"
	],

	fr:[
		"Attention! 51 pour cent que l'objet est un étranger!",
		"La structure de l'ADN montre que les ancêtres de l'objet sont d'origine extraterrestre",
		"Une substance inconnue a été détectée dans le sang, probablement cet objet est un ovni",
		"fond radioactif dit que parmi les amis de l'objet est étranger",
		"niveau élevé de rayonnement inconnu, quelqu'un essaie de vous duper, essayez à nouveau",
		"Soit l'objet a récemment traité avec un étranger, soit il est lui-même étranger",
		"Scanner les yeux de l'objet détecté qu'il avait récemment vu un extraterrestre sous forme humaine",
		"L'objet ne le soupçonne pas, mais il a un étranger dans sa famille",
		"le rayonnement gamma dépasse la norme, très probablement, nous avons affaire à un objet d'origine surnaturelle",
		"Il y a des soupçons que la mémoire de l'objet a été réécrite, et dans son passé il connaissait le secret de quelqu'un",
		"Le champ énergétique de l'objet contient un rayonnement inconnu, probablement de ses amis",
		"Le balayage a détecté que les vêtements de l'objet touchaient l'étranger",
		"Rayonnement inconnu détecté, balayage répété",
		"Selon les données de numérisation, l'objet est confronté au phénomène de l'existence extraterrestre",
		"Le subconscient de l'objet cache un secret très important",
		"Le subconscient de l'objet est basé, répétons l'analyse",
		"Laissez l'objet montrer le numéro trois avec vos doigts et répétez le balayage",
		"Basculez en mode détecteur de vérité et laissez l'objet répondre à la question s'il aime le vert",
		"Cent pour cent que l'objet provient de notre système solaire, mais il n'est pas sûr de quelle planète",
		"Le balayage montre que l'objet a des capacités télépathiques, il ne le sait pas ou ne l'admet pas",
		"La recherche de la mémoire montre qu'il y a au moins une personne extraterrestre dans l'environnement quotidien de l'objet",
		"L'analyse du champ d'énergie d'un objet est très similaire à celle de la zone 51"
	],

	de: [
		"Achtung! 51 Prozent, dass das Objekt ein Alien ist!",
		"Die DNA-Struktur zeigt, dass die Vorfahren des Objekts außerirdischen Ursprungs sind",
		"Es wurde eine unbekannte Substanz im Blut gefunden, wahrscheinlich hat dieses Objekt ein UFO-Problem",
		"Radioaktiver Hintergrund sagt, dass unter den Freunden des Objekts fremd ist",
		"Unbekannte Strahlung, jemand versucht Sie zu täuschen, versuchen Sie es erneut",
		"Entweder hat sich das Objekt kürzlich mit einem Außerirdischen befasst, oder er ist selbst ein Außerirdischer",
		"Beim Scannen der Augen des Objekts wurde festgestellt, dass er kürzlich einen Außerirdischen in menschlicher Gestalt gesehen hatte",
		"Das Objekt ahnt das nicht, aber er hat einen Ausländer in seiner Familie",
		"Gammastrahlung übersteigt die Norm sehr wahrscheinlich, wir haben es mit einem Objekt von überirdischem Ursprung zu tun",
		"Es gibt den Verdacht, dass das Gedächtnis des Objekts umgeschrieben wurde, und in seiner Vergangenheit kannte er jemandes Geheimnis.",
		"Das Energiefeld des Objekts enthält unbekannte Strahlung, möglicherweise von seinen Freunden",
		"Beim Scannen wurde festgestellt, dass die Kleidung des Objekts den Außerirdischen berührte.",
		"Unbekannte Strahlung erkannt, Scan wiederholen",
		"Laut Scan-Daten handelt es sich bei dem Objekt um das Phänomen der außerirdischen Existenz.",
		"Das Unterbewusstsein des Objekts verbirgt ein sehr wichtiges Geheimnis",
		"Das Unterbewusstsein des Objekts basiert, lassen Sie uns den Scan wiederholen",
		"Lassen Sie das Objekt die Nummer drei mit Ihren Fingern anzeigen und wiederholen Sie den Scan",
		"Wechseln Sie in den Wahrheitserkennungsmodus und lassen Sie das Objekt die Frage beantworten, ob es grün mag",
		"Einhundert Prozent, dass das Objekt aus unserem Sonnensystem stammt, aber es ist ungewiss, von welchem ​​Planeten es stammt.",
		"Das Scannen zeigt, dass das Objekt telepathische Fähigkeiten hat, es weiß es einfach nicht oder gibt es nicht zu.",
		"Gedächtnisforschung zeigt, dass es mindestens eine außerirdische Person im alltäglichen Umfeld des Objekts gibt",
		"Das Scannen des Energiefelds eines Objekts ist dem Energiefeld in Zone 51 sehr ähnlich."
	],

	it: [
		"Attenzione! Il 51 percento che l'oggetto è un alieno!",
		"La struttura del DNA mostra che gli antenati dell'oggetto sono di origine extraterrestre",
		"Nel sangue è stata rilevata una sostanza sconosciuta, probabilmente questo oggetto ha una preoccupazione per gli UFO",
		"lo sfondo radioattivo dice che tra gli amici dell'oggetto è alieno",
		"alto livello di radiazioni sconosciute, qualcuno sta cercando di ingannarti, riprovare",
		"O l'oggetto ha recentemente avuto a che fare con un alieno o è lui stesso un alieno",
		"La scansione degli occhi dell'oggetto ha rivelato che aveva visto di recente un alieno in Forma umana",
		"L'oggetto non sospetta questo, ma ha un alieno nella sua famiglia",
		"la radiazione gamma supera la norma, molto probabilmente, abbiamo a che fare con un oggetto di origine soprannaturale",
		"Si sospetta che la memoria dell'oggetto sia stata riscritta e in passato conosceva il segreto di qualcuno",
		"Il campo energetico dell'oggetto contiene radiazioni sconosciute, possibilmente dai suoi amici",
		"La scansione ha rilevato che l'abbigliamento dell'oggetto toccava l'alieno",
		"Rilevata radiazione sconosciuta, ripetere la scansione",
		"Secondo i dati di scansione, l'oggetto sta affrontando il fenomeno dell'esistenza extraterrestre",
		"Il subconscio dell'oggetto nasconde un segreto molto importante",
		"L'inconscio dell'oggetto si basa, ripetiamo la scansione",
		"Lascia che l'oggetto mostri il numero tre con le dita e ripeti la scansione",
		"Passa alla modalità rilevatore di verità e lascia che l'oggetto risponda alla domanda se gli piace il verde",
		"Il cento percento dell'oggetto proviene dal nostro sistema solare, ma non è sicuro da quale pianeta",
		"La scansione mostra che l'oggetto ha abilità telepatiche, semplicemente non lo sa o non lo ammette",
		"La ricerca sulla memoria mostra che esiste almeno una persona extraterrestre nell'ambiente quotidiano dell'oggetto",
		"La scansione del campo energetico di un oggetto è molto simile al campo energetico nella zona 51"
	],

	es: [
		"Atención! 51 por ciento de que el objeto es un extraterrestre!",
		"La estructura del ADN muestra que los antepasados ​​del objeto son de origen extraterrestre",
		"Se detectó una sustancia desconocida en el conjunto de sangre, probablemente este objeto tiene una preocupación de ovnis",
		"El fondo radiactivo dice que entre los amigos del objeto es ajeno",
		"alto nivel de radiación desconocida, alguien intenta engañarte, inténtalo de nuevo",
		"O el objeto ha tratado recientemente con un extraterrestre o él mismo es un extraterrestre",
		"Al escanear los ojos del objeto se detectó que recientemente había visto un extraterrestre en forma humana",
		"El objeto no sospecha esto, pero tiene un extraterrestre en su familia",
		"La radiación gamma excede la norma, muy probablemente, estamos tratando con un objeto de origen sobrenatural",
		"Hay sospechas de que la memoria del objeto fue reescrita, y en su pasado sabía el secreto de alguien",
		"El campo energético del objeto contiene radiación desconocida, posiblemente de sus amigos",
		"Al escanear se detectó que la ropa del objeto estaba tocando al alienígena",
		"Radiación desconocida detectada, repetir exploración",
		"Según los datos escaneados, el objeto está lidiando con el fenómeno de la existencia extraterrestre",
		"El subconsciente del objeto esconde un secreto muy importante",
		"El subconsciente del objeto está basado, repitamos el escaneo",
		"Deje que el objeto muestre el número tres con los dedos y repita el escaneo",
		"Cambie al modo detector de verdad y deje que el objeto responda la pregunta si le gusta el verde",
		"Cien por ciento de que el objeto proviene de nuestro sistema solar, pero no está seguro de qué planeta",
		"El escaneo muestra que el objeto tiene habilidades telepáticas, simplemente no lo sabe o no lo admite",
		"La investigación de la memoria muestra que hay al menos una persona extraterrestre en el entorno cotidiano del objeto",
		"Escanear el campo de energía de un objeto es muy similar al campo de energía en la zona 51"
	]
}

export default alienAnswer;