const truthAnswer = {

	en: [
	    
	   "This is similar to the truth",
	    "one hundred and two percent is a lie",
	    "something is wrong, but it seems to be the truth",
	    "After analyzing the voice, I detected 51% of the truth",
	    "Something went wrong, repeat the scan again",
	    "Sounds convincing, but unfortunately this is not entirely true",
	    "If that's true, I'm a vacuum cleaner",
	    "considering the heartbeat is true",
	    "After analyzing the voice, I detected 30% of the lies",
	    "Nobody is perfect, but why lie?",
	    "everyone has something to hide, but here I see the truth",
	    "I feel a bit nervous, it's probably not true",
	    "After analyzing the voice, I detected 90% of the truth",
	    "I think it's a joke because it's not true",
	    "This is definitely not a lie",
	    "If the Earth is flat, then it is also true",
	    "tell me why are you lying?",
	    "After analyzing the voice, I found it to be true",
	    "I detected activity in the left hemisphere of the brain, apparently this is a lie",
	    "After analyzing the voice, I found it to be a lie",
	    "I sense high frequency tension, apparently it's true",
	    "you can't fool the Universe and don't lie to me",
	    "The object doesn't lie"
	],

	pl:[
		"To jest podobne do prawdy",
		"sto dwa procent, że to kłamstwo",
		"coś jest nie tak, ale wydaje się, że to jest prawda",
		"Po analizie głosu, wykryłem 51% prawdy",
		"Coś poszło nie tak, powtóż jescze raz scanowanie",		
		"Brzmi przekonujaco, ale niestety to nie jest do końca  prawdą",
		"Jeżeli to jest prawdą, to ja jestem odkurzaczem",
		"biorąc pod uwagę bicie serca, to prawda",
		"Po analizie głosu, wykryłem 30% kłamstwa",
		"Nikt nie jest idealny, ale po co tak kłamać",
		"każdy ma coś do ukrycia, ale tutaj widzę prawdę",
		"Czuję lekkie zdenerwowanie, prawdopodobnie to nie jest prawdą",
		"Po analizie głosu, wykryłem 90% prawdy",
		"Myślę, że to żart, bo to nie jest prawdą",
		"To zdecydowanie nie jest klamstwem",
		"Jezeli Ziemia jest płaska, to wtedy też jest prawdą",
		"powiedz, po co kłamiesz?",
		"Po analizie głosu, wykryłem, że to jest prawdą",
		"Wykryłem aktywność w lewej półkuli mózgu, najwyrażniej to jest kłamstwem",
		"Po analizie głosu, wykryłem, że to jest kłamstwem",
		"Wyczuwam napiecie wysokiej częstotliwości,  najwyraźnije to jest prawda",
		"Wszechświat nie oszukasz, i mi też nie kłam",
		"Objekt nie kłamie"
	],

	ru: [
		"Это похоже на правду",
		"сто два процента это ложь",
		"Что-то здесь не так, но, похоже, это правда",
		"Проанализировав голос, я обнаружил 51% правды",	
		"Что-то пошло не так, повторите сканирование",
		"Звучит убедительно, но, к сожалению, это не совсем так",
		"Если это правда, то я пылесос",
		"учитывая сердцебиение это правда",		
		"Никто не идеален, но зачем врать?",
		"Проанализировав голос, я обнаружил 30% лжи",
		"каждому есть что скрывать, но здесь я вижу правду",
		"чувствую переживание, это, вероятно, ложь",
		"Проанализировав голос, я обнаружил 90% правды",
		"Я думаю, что это шутка, потому что это не правда",
		"Это определенно не ложь",
		"это также верно, кaк и то, что Земля плоская",
		"скажи почему ты врешь?",
		"Проанализировав голос, я обнаружил, что это правда",
		"Я обнаружил активность в левом полушарии головного мозга, видимо, это ложь",
		"Проанализировав голос, я обнаружил, что это ложь",
		"Я чувствую напряжение высокой частоты, по-видимому, это правда",
		"ты не можешь обмануть вселенную и мне не лги",
		"Объект не лжет"
	],

	es: [
		"Parece la verdad",
		"ciento dos por ciento es una mentira",
		"Algo está mal aquí, pero parece ser cierto",
		"Después de analizar la voz, encontré el 51% de la verdad",
		"Algo salió mal, intenta escanear de nuevo",
		"Suena convincente, pero desafortunadamente no es así",
		"Si es verdad, entonces soy una aspiradora",
		"dado el latido del corazón es verdad",
		"Nadie es perfecto, pero ¿por qué mentir?",
		"Después de analizar la voz, encontré el 30% de las mentiras",
		"Todos tienen algo que ocultar, pero aquí veo la verdad",
		"siente la experiencia, esto es probablemente una mentira",
		"Después de analizar la voz, encontré el 90% de la verdad",
		"Creo que esto es una broma porque no es verdad",
		"Esto definitivamente no es una mentira",
		"También es cierto que la Tierra es plana",
		"dime por qué estás mintiendo?",
		"Después de analizar la voz, descubrí que era verdad",
		"Encontré actividad en el hemisferio izquierdo del cerebro, aparentemente esto es una mentira",
		"Después de analizar la voz, me pareció una mentira",
		"Siento el voltaje de alta frecuencia, aparentemente es verdad",
		"No puedes engañar al universo y no me mientas",
		"El objeto no miente"
	],

	it: [
		"Questo è simile alla verità",
		"centodue percento, è una bugia",
		"qualcosa non va, ma sembra essere la verità",
		"Dopo aver analizzato la voce, ho rilevato il 51% della verità",
		"Qualcosa è andato storto, ripetere la scansione ancora una volta",
		"Sembra convincente, ma sfortunatamente non è del tutto vero",
		"Se questo è vero, allora sono un aspirapolvere",
		"dato che il battito del cuore è vero",
		"Dopo aver analizzato la voce, ho rilevato bugie del 30%",
		"Nessuno è perfetto, ma perché mentire così",
		"tutti hanno qualcosa da nascondere, ma qui vedo la verità",
		"Mi sento un po 'nervoso, probabilmente non è vero",
		"Dopo aver analizzato la voce, ho rilevato il 90% della verità",
		"Penso che sia uno scherzo perché non è vero",
		"Questa sicuramente non è una bugia",
		"Se la Terra è piatta, allora è anche vero",
		"dire, perché stai mentendo?",
		"Dopo aver analizzato la voce, ho scoperto che era vera",
		"Ho rilevato attività nell'emisfero sinistro del cervello, apparentemente questa è una bugia",
		"Dopo aver analizzato la voce, ho scoperto che era una bugia",
		"Sento la tensione ad alta frequenza, apparentemente questa è la verità",
		"Non ingannerai l'universo e non mentirmi",
		"L'oggetto non mente"
	],

	de: [
		"Das ist der Wahrheit ähnlich",
		"einhundert und zwei Prozent, das ist eine Lüge",
		"etwas stimmt nicht, aber es scheint die Wahrheit zu sein",
		"Nachdem ich die Stimme analysiert hatte, entdeckte ich 51% der Wahrheit.",
		"Etwas ist schief gelaufen, noch einmal scannen",
		"Klingt überzeugend, ist aber leider nicht ganz richtig",
		"Wenn das stimmt, dann bin ich ein Staubsauger",
		"Angesichts des Herzschlags ist wahr",
		"Nach der Analyse der Stimme habe ich 30% Lügen entdeckt",
		"Niemand ist perfekt, aber warum so lügen",
		"Jeder hat etwas zu verbergen, aber hier sehe ich die Wahrheit",
		"Ich bin etwas nervös, es ist wahrscheinlich nicht wahr",
		"Nachdem ich die Stimme analysiert hatte, entdeckte ich 90% der Wahrheit.",
		"Ich denke, es ist ein Witz, weil es nicht wahr ist",
		"Das ist definitiv keine Lüge",
		"Wenn die Erde flach ist, ist es auch wahr",
		"Sag, warum lügst du?",
		"Nachdem ich die Stimme analysiert hatte, stellte ich fest, dass sie wahr ist.",
		"Ich habe eine Aktivität in der linken Gehirnhälfte festgestellt, anscheinend ist dies eine Lüge.",
		"Nachdem ich die Stimme analysiert hatte, stellte ich fest, dass es eine Lüge war.",
		"Ich spüre Hochfrequenzspannung, anscheinend ist das die Wahrheit.",
		"Du wirst das Universum nicht zum Narren halten und mich nicht anlügen",
		"Das Objekt lügt nicht"
	],

	ja: [
		"これは真実に似ています",
		"百二パーセントは嘘です",
		"何かが間違っていますが、それは真実のようです",
		"声を分析した後、真実の51％を検出しました",
		"何かがうまくいきませんでした。もう一度スキャンを繰り返してください",
		"説得力があるように聞こえますが、残念ながらこれは完全に真実ではありません",
		"それが本当なら、私は掃除機です",
		"ハートビートが正しいと考える",
		"声を分析した後、嘘の30％を検出しました",
		"誰も完璧ではありませんが、なぜ嘘をつくのですか？",
		"誰もが隠すものを持っていますが、ここで私は真実を見る",
		"少し緊張します",
		"声を分析した後、真実の90％を検出しました",
		"冗談だと思う",
		"これは間違いなく嘘ではありません",
		"地球が平らであれば、それも真実です",
		"なぜ嘘をついているのですか？",
		"声を分析した後、私はそれが真実であることがわかりました",
		"脳の左半球で活動を検出しました。明らかにこれは嘘です",
		"声を分析した後、私はそれが嘘であることがわかりました",
		"高周波の緊張を感じます、どうやらそれは本当です",
		"あなたは宇宙をだますことができず、私に嘘をつかない",
		"オブジェクトは嘘をつかない"
	],

	fr:[
		"Ceci est similaire à la vérité",
		"cent deux pour cent est un mensonge",
		"quelque chose ne va pas, mais cela semble être la vérité",
		"Après avoir analysé la voix, j'ai détecté 51% de la vérité",
		"Quelque chose s'est mal passé, recommencez le scan",
		"Cela semble convaincant, mais malheureusement, ce n'est pas tout à fait vrai",
		"Si c'est vrai, je suis un aspirateur",
		"considérant que le battement de coeur est vrai",
		"Après avoir analysé la voix, j'ai détecté 30% des mensonges",
		"Personne n'est parfait, mais pourquoi mentir?",
		"tout le monde a quelque chose à cacher, mais ici je vois la vérité",
		"Je me sens un peu nerveux, ce n'est probablement pas vrai",
		"Après avoir analysé la voix, j'ai détecté 90% de la vérité",
		"Je pense que c'est une blague parce que ce n'est pas vrai",
		"Ce n'est certainement pas un mensonge",
		"Si la Terre est plate, alors c'est aussi vrai",
		"Dites pourquoi vous mentez?",
		"Après avoir analysé la voix, je l'ai trouvée vraie",
		"J'ai détecté une activité dans l'hémisphère gauche du cerveau, apparemment c'est un mensonge",
		"Après avoir analysé la voix, j'ai trouvé que c'était un mensonge",
		"Je sens la tension haute fréquence, apparemment c'est vrai",
		"vous ne pouvez pas tromper l'univers et ne me mentez pas",
		"L'objet ne ment pas"
	],

	zh:[
		"这类似于事实",
		"百分之一百二十是谎言",
		"某事是错误的，但这似乎是事实",
		"分析声音之后，我发现了51％的真相",
		"出了点问题，请再次重复扫描",
		"听起来令人信服，但不幸的是，这并不完全正确",
		"如果是真的，我就是吸尘器",
		"认为心跳是真的",
		"分析声音后，我发现了30％的谎言",
		"没有人是完美的，但是为什么要说谎？",
		"每个人都有隐藏的东西，但在这里我看到了真相",
		"我有点紧张，这可能不是真的",
		"分析声音后，我发现了90％的真相",
		"我认为这是个玩笑，因为那不是真的",
		"这绝对不是谎言",
		"如果地球是平坦的，那也是事实",
		"说你为什么说谎？",
		"分析声音后，我发现它是真实的",
		"我检测到大脑左半球有活动，这显然是谎言",
		"分析声音之后，我发现这是一个谎言",
		"我感觉到高频张力，显然是真的",
		"你不能愚弄宇宙，也不要对我说谎",
		"该对象没有说谎"
	]
}

export default truthAnswer;